#' Execute Code against a Git Ref
#'
#' Executes a function against a specified a Git repository reference.
#' `git_exec()` operates by checking out the reference and executing
#' the function. By default, `git_exec()` restores the repository to it's
#' original HEAD but restoration may fail if Git conflicts are generated by
#' `fn`.
#'
#' @param ref A [git2r::checkout()] supported ref object or a string identifying
#'    a Git ref (e.g. a branch name, tag name or commit hash). The `repo`
#'    argument is required for string inputs.
#' @param fn A function to execute.
#' @param ... Arguments passed to `fn.`
#' @param repo A `git2r::git_repository` object or
#'   [discoverable](git2r::discover_repository) path to a repository
#'   (default: "."); _required_ if `ref` is a string.
#' @param restore_head Whether to restore the repository's HEAD to its original
#'   position, as a boolean (default: `TRUE`).
#'
#' @returns
#' The result of `fn`.
#'
#' @export
git_exec <- function(ref, fn, ..., repo = NULL, restore_head = TRUE) {
  if (restore_head) anchor_head(repo)
  if (!is_git2r_ref(ref) && length(ref) > 1) {
    stop("`ref` should be a single git ref. Did you mean to use `git_iterate()`?")
  }

  if (is_git2r_ref(ref)) {
    git2r::checkout(ref)
  } else {
    git2r::checkout(repo, ref)
  }

  fn(...)
}
